---
######################################################
### Deployment Configuration Construct              ##
######################################################
apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: dc-sample-app
    name: dc-sample-app
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: jboss/wildfly
      from:
        kind: DockerImage
        name: jboss/wildfly
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: dc-sample-app
    name: dc-sample-app
  spec:
    replicas: 1
    selector:
      app: dc-sample-app
      deploymentconfig: dc-sample-app
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: dc-sample-app
          deploymentconfig: dc-sample-app
      spec:
        containers:
        - env:
          ########################################
          ## Secrets                            ##
          ########################################
          - name: KEYCLOAK_TOKEN_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: scr-env-sample-app-secret
                key: scr-KEYCLOAK_TOKEN_CLIENT_SECRET

          ########################################
          ## Environmental Variables            ##
          ########################################
          - name: APPLICATION_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: cm-env-sample-app-environment
                key: sample-app-APPLICATION_SERVICE_PORT
          - name: APPLICATION_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: cm-env-sample-app-environment
                key: sample-app-APPLICATION_SERVICE_URL
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: cm-env-sample-app-environment
                key: sample-app-DEBUG
          - name: FORM_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: cm-env-sample-app-environment
                key: sample-app-FORM_SERVICE_PORT
          - name: FORM_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: cm-env-sample-app-environment
                key: sample-app-FORM_SERVICE_URL
          - name: KEYCLOAK_AUTH_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: cm-env-sample-app-environment
                key: sample-app-KEYCLOAK_AUTH_SERVER_URL
          - name: KEYCLOAK_REALM
            valueFrom:
              configMapKeyRef:
                name: cm-env-sample-app-environment
                key: sample-app-KEYCLOAK_REALM
          - name: KEYCLOAK_TOKEN_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: cm-env-sample-app-environment
                key: sample-app-KEYCLOAK_TOKEN_CLIENT_ID
          - name: KEYCLOAK_VALIDATION_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: cm-env-sample-app-environment
                key: sample-app-KEYCLOAK_VALIDATION_CLIENT_ID
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: cm-env-sample-app-environment
                key: sample-app-NODE_ENV
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: cm-env-sample-app-environment
                key: sample-app-PORT
          - name: REFERENCE_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: cm-env-sample-app-environment
                key: sample-app-REFERENCE_SERVICE_PORT
          - name: REFERENCE_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: cm-env-sample-app-environment
                key: sample-app-REFERENCE_SERVICE_URL

          image: jboss/wildfly
          name: dc-sample-app
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            ######################################################
            ## Resource Management                              ##
            ## CPU Initial Request    = 0.5 cores               ##
            ## Memory Initial Request = 512 MB                  ##
            ## CPU Upper Limit        = 1.0 cores               ##
            ## Memory Upper Limit     = 1024 MB                 ##
            ######################################################
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2048Mi"

    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - dc-sample-app
        from:
          kind: ImageStreamTag
          name: dc-sample-app:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
kind: List
metadata: {}
---
#######################################################
#### End of Section                                  ##
#######################################################
